language: go

go:
  - 1.12
  - 1.13

env:
  - GO111MODULE=on

os:
  - linux
  - osx
  - windows

before_script:
  - go install

script:
  - go test ./...

notifications:
  email:
    - harrybrown98@gmail.com