language: go

stages:
  - diff
  - test

go:
  - 1.13

before_script:
  - go build
  - go install
  - go clean -testcache

script:
  - go test ./...

notifications:
  email:
    - harrybrown98@gmail.com