language: go

stages:
  - diff
  - test

go:
  - 1.11
  - 1.12
  - 1.13

env:
  - GO111MODULE=on

before_script:
  - go mod tidy
  - go install

script:
  - go test ./...

notifications:
  email:
    - harrybrown98@gmail.com