language: go

go:
  - 1.11
  - 1.12
  - 1.13

env:
  - GO111MODULE=on

os:
  - linux
  - osx
  - windows

jobs:
  include:
    - go: 1.11
      before_install:
        - go get -u $(go list -f '{{ join .Imports "\n" }}' github.com/harrybrwn/apizza/... | grep '^github.com/.*' | grep 'apizza' -v)

before_script:
  - go install

script:
  - go test ./...

notifications:
  email:
    - harrybrown98@gmail.com