language: go

go:
  - 1.12
  - 1.13

env:
  global:
    - GO111MODULE=on
os:
  - linux
  - osx
  - windows
before_script:
  - go install

script:
  - go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - harrybrown98@gmail.com